
insert into passage (name, version_id) values ("morris story",1);
INSERT INTO `paragraph` (version_id,passage_id,paragraph_id, paragraph) values  (1,1,1,'Mike and Morris lived in the same village. While Morris owned the largest jewelry shop in the village, Mike was a poor farmer. Both had large families with many sons, daughters-in-law and grandchildren. One fine day, Mike, tired of not being able to fed his family, decided to leave the village and move to the city where he was certain to earn enough to feed everyone.Along with his family, he left the village for the city. At night, they stopped under a large tree. There was a stream running nearby where they could freshen up themselves. He told his sons to clear the area below the tree, he told his wife to fetch water and he instructed his daughters-in-law to make up the fire and started cutting wood from the tree himself. They didn’t knew that in the branches of the tree, there was a thief hiding. He watched as Mike’s family worked together and also noticed that they had nothing to cook. Mike’s wife also thought the same and asked her husband ” Everything is ready but what shall we eat ? ” Mike raised his hands to heaven and said ” Don’t worry. He is watching all this from above. He will help us.”'),(1,1,2,'The thief got worried as he had seen that the family was large and worked well together. Taking advantage of the fact that they did not know he was hiding in the branches, he decided to make a quick escape. He climbed down safely when they were not looking and ran for his life. But, he left behind the bundle of stolen jewels and money which dropped into Mike’s lap. Mike opened it and jumped with joy when he saw the contents. The family gathered all their belongings and returned to the village. There was great excitement when they told everyone how they got rich.'),(1,1,3,'Morris thought that the tree was miraculous and this was a nice and quick way to earn some money. He ordered his family to pack some clothes and they set off as if on a journey. They also stopped under the same tree and Morris started commanding everyone as Mike had done. But no one in his family was willing to obey his orders. Being a rich family, they were used to having servants all around. So, the one who went to the river to fetch water enjoyed a nice bath. The one who went to get wood for fire went off to sleep. Morris’s wife said ” Everything is ready but what shall we eat ?” Morris raised his hands and said, ” Don’t worry. He is watching all this from above. He will help us.”'),(1,1,4,'As soon as he finished saying, the thief jumped down from the tree with a knife in hand. Seeing him, everyone started running here and there to save their lives. The thief stole everything they had and Morris and his family had to return to the village empty handed, having lost all their valuables that they had taken with them.');

INSERT INTO `question` (version_id,passage_id,question_id,question) VALUES (1,1,1,'Why did Mike and his family decide to rest under the thief’s tree ?'),(1,1,2,'Which of the following best describes Morris ?'),(1,1,3,' What did Mike mean when he said “He is watching all this from above”?'),(1,1,4,'Why did the thief return to the tree?'),(1,1,5,'How did the fellow villagers react to Mike getting rich overnight?');


INSERT INTO `multiple_option` (version_id,question_id,option_id,option_text) VALUES (1,1,1,'Being a large family, they knew that they could easily defeat the thief'),(1,1,2,'It was a convenient spot for taking a halt at night'),(1,1,3,'There was a stream nearby and wood enough to build a house'),(1,1,4,'That was the only large tree that could shelter their large family'),
 (1,2,5,'He was a rich businessman'),(1,2,6,'He bullied his wife'),(1,2,7,'He paid his servants well'),(1,2,8,'He was greedy and imitated Mike'),
 (1,3,9,'Being a large family, they knew that they could easily defeat the thief'),(1,3,10,'It was a convenient spot for taking a halt at night'),(1,3,11,'There was a stream nearby and wood enough to build a house'),(1,3,12,'That was the only large tree that could shelter their large family');


INSERT INTO `answer` (version_id,question_id,option_id) values (1,1,2),(1,2,8),(1,3,10);
